---
# This playbook contains tasks for installing system tools

# Install GVFS - userspace virtual filesystem
- name: Install "gvfs-fuse" package
  apt:
    name: gvfs-fuse
    state: present

# Install MTP Tools
- name: INstall "mtp-tools" package
  apt:
    name: mtp-tools
    state: present
