---
# This playbook contains tasks for installing Steam
# Based on https://linuxconfig.org/how-to-install-steam-on-ubuntu-16-04-xenial-xerus
- name: Install Steam client
  apt:
    name: steam-installer

# Add manual steps, in case of the above failing?
