---
# This playbook contains workstation plays that will be run on all nodes

# Plays to include for applications
- include: includes/applications/applications-audio.yml
- include: includes/applications/applications-office.yml

# Plays to include for games
- include: includes/games/games-steam.yml

# Plays to include for development tools
- include: includes/graphics/graphics-gimp.yml
#- include: includes/graphics/graphics-darktable.yml

# Plays to include for networking tools
- include: includes/network/network-browsers.yml
- include: includes/network/network-chat.yml
- include: includes/network/network-download-tools.yml
