---
# This playbook contains tasks for installing various chat tools

- name: Update repo cache and upgrade packages
  apt:
    upgrade: yes
    update_cache: yes
  register: apt_result
  until: apt_result|success
  retries: 3
  delay: 1
  ignore_errors: yes

- name: Retry, if needed, using command apt-get update
  command: apt-get update
  become: true
  when: apt_result|failed

- name: Retry, if needed, using command apt-get update
  command: apt-get upgrade
  become: true
  when: apt_result|failed

- name: Install the Corebird Twitter client
  apt:
    name: corebird
    state: present
    #update_cache: yes

- name: Install the irssi IRC client
  apt:
    name: irssi
    state: present
    #update_cache: yes
