---
# This playbook contains tasks for installing various web browsers
# @todo - Add include for Firefox Developer Edition
# Chromium
- name: Install Chromium
  apt:
    name: chromium-browser
    state: present
    #update_cache: yes
    
- name: Install Chromium codecs
  apt:
    name:
      - chromium-codecs-ffmpeg
      - chromium-codecs-ffmpeg-extra
    state: present

# elinks
- name: Install elinks
  apt:
    name: elinks
    state: present
    #update_cache: yes

- name: Install elinks data files
  apt:
    name: elinks-data
    state: present
    #update_cache: yes

- name: Install elinks documentation
  apt:
    name: elinks-doc
    state: present
    #update_cache: yes

# w3m
- name: Install w3m
  apt:
    name: w3m
    state: present
    #update_cache: yes

- name: Install w3m inline image extension
  apt:
    name: w3m-img
    state: present
    #update_cache: yes

