---
# This playbook contains tasks for installing various web browsers

- name: Update repo cache and upgrade packages
  apt:
    upgrade: yes
    update_cache: yes
  register: apt_result
  until: apt_result|success
  retries: 3
  delay: 1
  ignore_errors: yes

- name: Retry, if needed, using command apt-get update
  command: apt-get update
  become: true
  when: apt_result|failed

- name: Retry, if needed, using command apt-get update
  command: apt-get upgrade
  become: true
  when: apt_result|failed

# Chromium
- name: Install Chromium
  apt:
    name: chromium-browser
    state: present
    #update_cache: yes

# elinks
- name: Install elinks
  apt:
    name: elinks
    state: present
    #update_cache: yes

- name: Install elinks data files
  apt:
    name: elinks-data
    state: present
    #update_cache: yes

- name: Install elinks documentation
  apt:
    name: elinks-doc
    state: present
    #update_cache: yes

# w3m
- name: Install w3m
  apt:
    name: w3m
    state: present
    #update_cache: yes

- name: Install w3m inline image extension
  apt:
    name: w3m-img
    state: present
    #update_cache: yes

