---
# This playbook contains tasks for installing cli tools

- name: "Working around Ansible lameness..."
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - aptitude

- name: Install "bleachbit" package
  apt:
    name: bleachbit
    state: present

- name: Install "redshift-gtk" package
  apt:
    name: redshift-gtk
    state: present

# To be swapped for KeePassXC - needs Snap support
#- name: Install "revelation" package
#  apt:
#    name: revelation
#    state: present

- name: Install "seahorse" package
  apt:
    name: seahorse
    state: present
