---
# This playbook contains tasks for installing vim

- name: Update repo cache and upgrade packages
  apt:
    update_cache: "yes"
  register: apt_result

- name: Install "exuberant-ctags" package
  apt:
    name: exuberant-ctags
    state: present

- name: Install "vim" package
  apt:
    name: vim
    state: present

- name: Install "vim-gtk" package
  apt:
    name: vim-gtk
    state: present
