---
# This playbook contains tasks for installing cli tools

- name: Update repo cache and upgrade packages
  apt:
    upgrade: yes
    update_cache: yes
  register: apt_result
  until: apt_result|success
  retries: 3
  delay: 1
  ignore_errors: yes

- name: Retry, if needed, using command apt-get update
  command: apt-get update
  become: true
  when: apt_result|failed

- name: Install "bleachbit" package
  apt:
    name: bleachbit
    state: present

- name: Install "redshift-gtk" package
  apt:
    name: redshift-gtk
    state: present

# To be swapped for KeePassXC - needs Snap support
#- name: Install "revelation" package
#  apt:
#    name: revelation
#    state: present

- name: Install "seahorse" package
  apt:
    name: seahorse
    state: present
