---
# This playbook contains tasks for installing cli tools

- name: Install "bleachbit" package
  apt:
    name: bleachbit
    state: present

- name: Install "seahorse" package
  apt:
    name: seahorse
    state: present
