---
# This playbook contains tasks for installing password related tools

- name: Install "apg" package
  apt:
    name: apg
    state: present
    
- name: Install "bitwarden" Snap package
  snap:
    name: bitwarden
    state: present

# Install Zeal Docs flatpak
- name: Install "KeePassXC" (Flathub)
  flatpak:
    name: org.keepassxc.KeePassXC
    state: present

- name: Install "pwgen" package
  apt:
    name: pwgen
    state: present

- name: Install "pass" package
  apt:
    name: pass
    state: present
