---
# This playbook contains tasks for installing vim

- name: "Working around Ansible lameness..."
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - aptitude

- name: Install "exuberant-ctags" package
  apt:
    name: exuberant-ctags
    state: present

- name: Install "vim" package
  apt:
    name: vim
    state: present

- name: Install "vim-gtk" package
  apt:
    name: vim-gtk
    state: present
