---
# This playbook contains tasks for installing password related tools

- name: Update repo cache and upgrade packages
  apt:
    update_cache: "yes"
  register: apt_result


- name: Install "apg" package
  apt:
    name: apg
    state: present

- name: Install "pwgen" package
  apt:
    name: pwgen
    state: present

- name: Install "pass" package
  apt:
    name: pass
    state: present
