---
# This playbook contains tasks for installing cli tools

- name: Install "bpytop" package
  pip:
    name: bpytop
    executable: pip3

- name: Install "conky-all" package
  apt:
    name: conky-all
    state: present

- name: Install "curl" package
  apt:
    name: curl
    state: present

- name: Install "htop" package
  apt:
    name: htop
    state: present

- name: Install "mc" package
  apt:
    name: mc
    state: present

- name: Install "tmux" package
  apt:
    name: tmux
    state: present

- name: Install "tmuxinator" package
  apt:
    name: tmuxinator
    state: present

- name: Install "topydo" package
  pip:
    name: topydo
    executable: pip3

- name: Install columns dependencies for "topydo" package
  pip:
    name: topydo[columns]
    executable: pip3
