---
# This playbook contains tasks for installing cli tools

- name: Update repo cache and upgrade packages
  apt:
    update_cache: "yes"
  register: apt_result

- name: Install "bleachbit" package
  apt:
    name: bleachbit
    state: present

- name: Install "redshift-gtk" package
  apt:
    name: redshift-gtk
    state: present

# To be swapped for KeePassXC - needs Snap support
#- name: Install "revelation" package
#  apt:
#    name: revelation
#    state: present

- name: Install "seahorse" package
  apt:
    name: seahorse
    state: present
