---
# This playbook contains tasks for installing Gimp
- name: Install Gimp
  apt:
    name: gimp
    state: present
    #update_cache: yes

- name: Install Gimp Help
  apt:
    name: gimp-help-en
    state: present
    #update_cache: yes

- name: Install Gimp Gutenprint
  apt:
    name: gimp-gutenprint
    state: present
    #update_cache: yes
