---
# This playbook contains tasks for installing Gimp

- name: Update repo cache and upgrade packages
  apt:
    upgrade: yes
    update_cache: yes
  register: apt_result
  until: apt_result|success
  retries: 3
  delay: 1
  ignore_errors: yes

- name: Retry, if needed, using command apt-get update
  command: apt-get update
  become: true
  when: apt_result|failed

- name: Retry, if needed, using command apt-get update
  command: apt-get upgrade
  become: true
  when: apt_result|failed

- name: Install Gimp
  apt:
    name: gimp
    #update_cache: yes

- name: Install Gimp Help
  apt:
    name: gimp-help-en
    #update_cache: yes
