---
# This playbook contains common plays that will be run on all nodes.

- name: Update repo cache and upgrade packages
  apt:
    upgrade: yes
    update_cache: yes
  register: apt_result
  until: apt_result|success
  retries: 3
  delay: 1
  ignore_errors: yes

- name: Retry, if needed, using command apt-get update
  command: apt-get update
  become: true
  when: apt_result|failed

- name: Retry, if needed, using command apt-get update
  command: apt-get upgrade
  become: true
  when: apt_result|failed

- include: theme.yml
- include: utilities-antivirus.yml
- include: utilities-cli.yml
- include: utilities-gui.yml
- include: utilities-passwords.yml
- include: utilities-powerline.yml
- include: utilities-syncthing.yml
- include: utilities-vim.yml
