---
# This playbook contains common plays that will be run on all nodes.

- name: Update repo cache and upgrade packages
  apt:
    upgrade: "yes"
    update_cache: "yes"
  register: apt_result
  until: apt_result|success
  retries: 3
  delay: 1
  ignore_errors: yes

- name: Retry, if needed, using command apt-get update
  command: apt-get update
  become: true
  when: apt_result|failed

- name: Retry, if needed, using command apt-get update
  command: apt-get upgrade
  become: true
  when: apt_result|failed

- include: theme.yml
- include: includes/development/development-python3.yml
- include: includes/development/development-zeal.yml
- include: includes/utilities/utilities-antivirus.yml
- include: includes/utilities/utilities-cli.yml
- include: includes/utilities/utilities-gui.yml
- include: includes/utilities/utilities-passwords.yml
- include: includes/utilities/utilities-powerline.yml
- include: includes/utilities/utilities-syncthing.yml
- include: includes/utilities/utilities-vim.yml
