---
# This playbook contains tasks for installing the desired theme/icons

- name: Check for arc-theme repo file
  local_action: stat path=/etc/apt/sources.list.d/arc-theme.list
  register: arc_theme_result

- name: Create repository file
  shell: echo 'deb {{ arc_repo }} /' >> /etc/apt/sources.list.d/arc-theme.list
  when: arc_theme_result|failed

- name: Add repository key
  apt_key:
    url: "{{ arc_repo }}/Release.key"
    state: present
  when: arc_theme_result|failed

- name: Update repository packagelist cache
  apt:
    update_cache: yes
  when: arc_theme_result|failed

- name: Install "arc-theme" package
  apt:
    name: arc-theme
    state: present
  when: arc_theme_result|failed

- name: Install "faenza-icon-theme" package
  apt:
    name: faenza-icon-theme
    state: present
