---
# This playbook contains tasks for installing cli tools

- name: Update repository packagelist cache
  apt:
    update_cache: yes

- name: Install "conky-all" package
  apt:
    name: conky-all
    state: present

- name: Install "curl" package
  apt:
    name: curl
    state: present

- name: Install "htop" package
  apt:
    name: htop
    state: present

- name: Install "mc" package
  apt:
    name: mc
    state: present