---
# This playbook contains tasks for installing cli tools

- name: Update repo cache and upgrade packages
  apt:
    upgrade: yes
    update_cache: yes
  register: apt_result
  until: apt_result|success
  retries: 3
  delay: 1
  ignore_errors: yes

- name: Retry, if needed, using command apt-get update
  command: apt-get update
  become: true
  when: apt_result|failed

- name: Retry, if needed, using command apt-get update
  command: apt-get upgrade
  become: true
  when: apt_result|failed

- name: Install "powerline" package
  apt:
    name: powerline
    state: present

- name: Get Powerline Symbols font
  shell: wget https://github.com/Lokaltog/powerline/raw/develop/font/PowerlineSymbols.otf https://github.com/Lokaltog/powerline/raw/develop/font/10-powerline-symbols.conf

- name: Move fonts file
  shell: mv PowerlineSymbols.otf /usr/share/fonts/

- name: Reload fonts cache
  shell: fc-cache -vf

- name: Move fonts config file
  shell: mv 10-powerline-symbols.conf /etc/fonts/conf.d/
