---
# This playbook contains tasks for installing anti-virus/rootkit scanners

- name: Update repo cache and upgrade packages
  apt:
    upgrade: yes
    update_cache: yes
  register: apt_result
  until: apt_result|success
  retries: 3
  delay: 1
  ignore_errors: yes

- name: Retry, if needed, using command apt-get update
  command: apt-get update
  become: true
  when: apt_result|failed

- name: Retry, if needed, using command apt-get update
  command: apt-get upgrade
  become: true
  when: apt_result|failed

- name: Install "chkrootkit" package
  apt:
    name: chkrootkit
    state: present

- name: Install "rkhunter" package
  apt:
    name: rkhunter
    state: present

- name: Install "clamav" package
  apt:
    name: clamav
    state: present

- name: Install "clamav-freshclam" package
  apt:
    name: clamav-freshclam
    state: present

- name: Install "clamtk" package
  apt:
    name: clamtk
    state: present
