---
# This playbook contains tasks for installing the desired theme

- name: Create repository file
  shell: echo "deb {{ syncthing_repo }} syncthing stable" >> /etc/apt/sources.list.d/syncthing.list

- name: Add repository key
  apt_key:
    url: "{{ syncthing_release_key }}"
    state: present

- name: Update repositories cache and install "foo" package
  apt:
    name: syncthing
    update_cache: yes