---
# This playbook contains tasks for installing cli tools

- name: Update repo cache and upgrade packages
  apt:
    upgrade: yes
    update_cache: yes
  register: apt_result
  until: apt_result|success
  retries: 3
  delay: 1
  ignore_errors: yes

- name: Retry, if needed, using command apt-get update
  command: apt-get update
  become: true
  when: apt_result|failed

- name: Retry, if needed, using command apt-get update
  command: apt-get upgrade
  become: true
  when: apt_result|failed

- name: Install "conky-all" package
  apt:
    name: conky-all
    state: present

- name: Install "curl" package
  apt:
    name: curl
    state: present

- name: Install "htop" package
  apt:
    name: htop
    state: present

- name: Install "mc" package
  apt:
    name: mc
    state: present
