---
# This playbook contains tasks for installing vim

- name: Update repository packagelist cache
  apt:
    update_cache: yes

- name: Install "exuberant-ctags" package
  apt:
    name: exuberant-ctags
    state: present

- name: Install "vim" package
  apt:
    name: vim
    state: present

- name: Install "vim-gtk" package
  apt:
    name: vim-gtk
    state: present