---
# This playbook contains tasks for installing dev tools

 - name: Update repo cache
  apt:
    update_cache: "yes"
  register: apt_result

- name: Install "python3-pip" package
  apt:
    name: python3-pip
    state: present