---
# This playbook contains tasks for installing the desired theme

- name: "Working around Ansible lameness..."
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - aptitude

- name: Check for arc-theme repo file
  local_action: stat path=/etc/apt/sources.list.d/zeal-developers-ubuntu-ppa-xenial.list
  register: zeal_result

- name: Add Zeal repository (PPA)
  apt_repository: repo='{{ zeal_repo }}' state=present

- name: Update repositories cache and install "zeal" package
  apt:
    name: zeal
    update_cache: "yes"
  when: zeal_result|failed