---
# This playbook contains tasks for installing dev tools

- name: "Working around Ansible lameness..."
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - aptitude

- name: Install "python3-pip" package
  apt:
    name: python3-pip
    state: present